language: ruby
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  
addons:
  code_climate:
    repo_token: 156fab7dad33afa6dd4b24ab5721a01e5bbb41c3f07c380195695102b7363e0a

script: bundle exec rspec spec
before_install:
 - gem update bundler
after_success:
  - bundle exec codeclimate-test-reporter
